[metadata]
  [metadata.heroku]
    root-package = "github.com/heroku/go-getting-started"
    additional-tools = ["foo","bar","bazzle"]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"
